RegistroAlumno/RegistroAlumno/Models/ListViewModel/GradoViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace RegistroAlumno.Models.ListViewModel
{
    public class GradoViewModel
    {
        [Required]
        [Display(Name = "ID")]
        public int Grd_id { get; set; }
        [Required]
        [StringLength(100)]
        [Display(Name = "GRADO")]
        public string Grd_nombre { get; set; }
        [Required]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [Display(Name = "FECHA DE CREACION")]
        public DateTime Created_at { get; set; }
        [Required]
        [DataType(DataType.Date)]
        [Display(Name = "FECHA DE ACTUALIZACION")]
        [DisplayFormat(DataFormatString ="{0:yyyy-MM-dd}", ApplyFormatInEditMode =true)]
        public DateTime Updated_at { get; set; }
    }
}

RegistroAlumno/RegistroAlumno/Controllers/GradoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using RegistroAlumno.Models;
using RegistroAlumno.Models.ListViewModel;

namespace RegistroAlumno.Controllers
{
    public class GradoController : Controller
    {
        // GET: Grado
        public ActionResult Index()
        {
            List<ListGradoViewModel> lst;
            using(RegistroData db = new RegistroData())
            {
                lst = (from d in db.grd_grado
                       select new ListGradoViewModel
                       {

                           Grd_id = d.grd_Id,
                           Grd_nombre = d.grd_Nombre,
                           Created_at = d.created_at,
                           Updated_at = d.updated_at

                       }).ToList();
            }

            return View(lst);
        }

        // GET: Grado/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Grado/Create
        public ActionResult Nuevo()
        {
            return View();
        }

        // POST: Grado/Create
        [HttpPost]
        public ActionResult Nuevo(GradoViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    using (RegistroData db = new RegistroData())
                    {
                        var oGrado = new grd_grado();

                        oGrado.grd_Id= model.Grd_id;
                        oGrado.grd_Nombre = model.Grd_nombre;
                        oGrado.created_at = model.Created_at;
                        oGrado.updated_at = model.Updated_at;

                        db.grd_grado.Add(oGrado);
                        db.SaveChanges();
                        


                    }
                    return RedirectToAction("/");
                }
                return View(model);

                
            }
            catch
            {
                return View();
            }
        }

        // GET: Grado/Edit/5
        public ActionResult Editar(int id)
        {
            GradoViewModel grado = new GradoViewModel();
            using(RegistroData db= new RegistroData())
            {
                var i = db.grd_grado.Find(id);
                grado.Grd_id = i.grd_Id;
                grado.Grd_nombre = i.grd_Nombre;
                grado.Created_at = i.created_at;
                grado.Updated_at = i.updated_at;
            }
            return View(grado);
        }

        // POST: Grado/Edit/5
        [HttpPost]
        public ActionResult Editar(GradoViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    using (RegistroData db = new RegistroData())
                    {
                        var i = db.grd_grado.Find(model.Grd_id);

                        i.grd_Id = model.Grd_id;
                        i.grd_Nombre = model.Grd_nombre;
                        i.created_at = model.Created_at;
                        i.updated_at = model.Updated_at;

                        db.Entry(i).State = System.Data.Entity.EntityState.Modified;
                        db.SaveChanges();



                    }
                    return RedirectToAction("/");
                }
                return View(model);


            }
            catch
            {
                return View();
            }
        }

        // GET: Grado/Delete/5
        public ActionResult Eliminar(int id)
        {
            
            using (RegistroData db = new RegistroData())
            {
                var i = db.grd_grado.Find(id);
                db.grd_grado.Remove(i);
                db.SaveChanges();

            }
            return RedirectToAction("/");
        }

        // POST: Grado/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

RegistroAlumno/RegistroAlumno/Views/Grado/Editar.cshtml
@model RegistroAlumno.Models.ListViewModel.GradoViewModel
@{
    ViewBag.Title = "Editar";
}

<h2>@ViewBag.Title</h2>


@using (Html.BeginForm("Editar", "Grado", FormMethod.Post))
{
    @Html.HiddenFor(d=>d.Grd_id)
   


    @Html.LabelFor(d => d.Grd_nombre)
    @Html.TextBoxFor(d => d.Grd_nombre, "", new { @class = "form-control" });


    @Html.HiddenFor(d=>d.Created_at)
    <br />

    @Html.LabelFor(d => d.Updated_at)
    <br />
    @Html.EditorFor(d => d.Updated_at, "", new { @class = "form-control" });



    <div style="padding-top: 5px">
        <input type="submit" value="Guardar" class="btn btn-primary" />
    </div>

}

RegistroAlumno/RegistroAlumno/Views/Grado/Index.cshtml
@model List<RegistroAlumno.Models.ListViewModel.ListGradoViewModel>
@{
    ViewBag.Title = "Grados";
}

<h2>@ViewBag.Title</h2>

<div class="row" style="text-align:right; padding:5px">
    <a href="~/Grado/Nuevo" class="btn btn-primary">Nuevo Grado</a>
</div>

<div class="row">
    <div class="col-md-12">
        <table class="table">
            <tr>
                <th>#</th>
                <th>Grado</th>
                <th>Fecha de Creación</th>
                <th>Fecha de Actualizacion</th>
                <th>Accion</th>

            </tr>
            @foreach (var i in Model)
            {
                <tr>
                    <td>@i.Grd_id</td>
                    <td>@i.Grd_nombre</td>
                    <td>@i.Created_at</td>
                    <td>@i.Updated_at</td>
                    <td>
                        <a href="~/Grado/Editar/@i.Grd_id" class="btn btn-success">Editar</a>
                        <a href="~/Grado/Eliminar/@i.Grd_id" class="btn alert-danger">Eliminar</a>
                    </td>
                </tr>
            }
        </table>

    </div>

</div>

RegistroAlumno/RegistroAlumno/Views/Grado/Nuevo.cshtml
@model RegistroAlumno.Models.ListViewModel.GradoViewModel
@{
    ViewBag.Title = "Nuevo";
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm("Nuevo", "Grado", FormMethod.Post))
{
    <div>
        @Html.LabelFor(d => d.Grd_id)
        @Html.TextBoxFor(d => d.Grd_id, "", new { @class = "form-control" })
        @Html.ValidationMessageFor(d=>d.Grd_id, null, new { @class="red"})
    </div>
    

    <div>
        @Html.LabelFor(d => d.Grd_nombre)
        @Html.TextBoxFor(d => d.Grd_nombre, "", new { @class = "form-control" })
        @Html.ValidationMessageFor(d => d.Grd_nombre, null, new { @class = "red" })
    </div>
   

    <div>
        @Html.LabelFor(d => d.Created_at)
        <br />
        @Html.EditorFor(d => d.Created_at, "", new { @class = "form-control" });
        @Html.ValidationMessageFor(d => d.Created_at, null, new { @class = "red" })
    </div>
    <br />
    <div>
        @Html.LabelFor(d => d.Updated_at)
        <br />
        @Html.EditorFor(d => d.Updated_at, "", new { @class = "form-control" });
        @Html.ValidationMessageFor(d => d.Updated_at, null, new { @class = "red" })
    </div>
   



    <div style="padding-top: 5px">
        <input type="submit" value="Guardar" class="btn btn-primary" />
    </div>

}