RegistroAlumno/RegistroAlumno/Models/ListViewModel/AlumnoViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace RegistroAlumno.Models.ListViewModel
{
    public class AlumnoViewModel
    {
        [Required]
        [Display(Name = "ID")]
        public int Alm_id { get; set; }
        [Required]
        [StringLength(300)]
        [Display(Name = "NOMBRE")]
        public string Alm_nombre { get; set; }
        [Required]
        [Display(Name = "EDAD")]
        public int Alm_edad { get; set; }
        [StringLength(100)]
        [Display(Name = "SEXO")]
        public string Alm_sexo { get; set; }
        [Required]
        [Display(Name = "GRADO")]
        public int Alm_id_grd { get; set; }
        [StringLength(100)]
        [Display(Name = "OBSERVACIONES")]
        public string Alm_observaciones { get; set; }
        [Required]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [Display(Name = "FECHA DE CREACION")]
        public DateTime Created_at { get; set; }
        [Required]
        [DataType(DataType.Date)]
        [Display(Name = "FECHA DE ACTUALIZACION")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime Updated_at { get; set; }
    }
}

RegistroAlumno/RegistroAlumno/Controllers/AlumnoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using RegistroAlumno.Models.ListViewModel;
using RegistroAlumno.Models;

namespace RegistroAlumno.Controllers
{
    public class AlumnoController : Controller
    {

        public int id;
        // GET: Alumno
        public ActionResult Index()
        {
            List<ListAlumnoViewModel> lst;
            using (RegistroData db = new RegistroData())
            {
                lst = (from d in db.alm_alumno
                       select new ListAlumnoViewModel
                       {
                           Alm_id = d.alm_id,
                           Alm_nombre = d.alm_nombre,
                           Alm_edad = d.alm_edad,
                           Alm_sexo = d.alm_sexo,
                           Alm_id_grd = d.alm_id_grd,
                           Alm_observaciones = d.alm_observaciones,
                           Created_at = d.created_at,
                           Updated_at = d.update_at

                       }).ToList();
            }

            return View(lst);
        }

        // GET: Alumno/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Alumno/Create
        public ActionResult Nuevo()
        {
            /*List<ListGradoViewModel> lst;*/
            /* using (RegistroData db = new RegistroData())
             {
                 lst = (from d in db.grd_grado
                        select new ListGradoViewModel
                        {
                            Grd_id = d.grd_Id,
                            Grd_nombre = d.grd_Nombre
                        }).ToList();
             }*/
            /*List<SelectListItem> items = lst.ConvertAll(d =>
            {
                return new SelectListItem()
                {
                    Text = d.Grd_nombre.ToString(),
                    Value = d.Grd_id.ToString(),
                    Selected = false
                    
                    
               
                };

                
            });*/
            RegistroData db = new RegistroData();
            ViewBag.items = db.grd_grado.ToList();
            return View();
        }

        // POST: Alumno/Create
        [HttpPost]
        public ActionResult Nuevo(AlumnoViewModel model)
        {
            try
            {

                // TODO: Add insert logic here
                if (ModelState.IsValid)
                {
                    using (RegistroData db = new RegistroData())
                    {
                        var oAlumno = new alm_alumno();

                        oAlumno.alm_id = model.Alm_id;
                        oAlumno.alm_nombre = model.Alm_nombre;
                        oAlumno.alm_edad = model.Alm_edad;
                        oAlumno.alm_sexo = model.Alm_sexo;
                        oAlumno.alm_id_grd = model.Alm_id_grd;
                        oAlumno.alm_observaciones = model.Alm_observaciones;
                        oAlumno.created_at = model.Created_at;
                        oAlumno.update_at = model.Updated_at;

                        db.alm_alumno.Add(oAlumno);
                        db.SaveChanges();



                    }
                    return RedirectToAction("/");
                }
                return View(model);
                
            }
            catch
            {
                return View();
            }
        }

        // GET: Alumno/Edit/5

        public ActionResult Editar(int id)
        {
            AlumnoViewModel oAlumno = new AlumnoViewModel();
            using (RegistroData db = new RegistroData())
            {
                var i = db.alm_alumno.Find(id);
                oAlumno.Alm_id= i.alm_id;
                oAlumno.Alm_nombre = i.alm_nombre;
                oAlumno.Alm_edad = i.alm_edad;
                oAlumno.Alm_sexo = i.alm_sexo;
                oAlumno.Alm_id_grd = i.alm_id_grd;
                oAlumno.Alm_observaciones = i.alm_observaciones;
                oAlumno.Created_at = i.created_at;
                oAlumno.Updated_at = i.update_at;
            }
            return View(oAlumno);
        }

        // POST: Alumno/Edit/5
        [HttpPost]
        public ActionResult Editar(AlumnoViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    using (RegistroData db = new RegistroData())
                    {
                        var oAlumno = db.alm_alumno.Find(model.Alm_id);

                        oAlumno.alm_id = model.Alm_id;
                        oAlumno.alm_nombre = model.Alm_nombre;
                        oAlumno.alm_edad = model.Alm_edad;
                        oAlumno.alm_sexo = model.Alm_sexo;
                        oAlumno.alm_id_grd = model.Alm_id_grd;
                        oAlumno.alm_observaciones = model.Alm_observaciones;
                        //oAlumno.created_at = model.Created_at;
                        oAlumno.update_at = model.Updated_at;

                        db.Entry(oAlumno).State = System.Data.Entity.EntityState.Modified;
                        db.SaveChanges();



                    }
                    return RedirectToAction("/");
                }
                return View(model);
            }
            catch
            {
                return View();
            }
        }

        // GET: Alumno/Delete/5

        public ActionResult Eliminar(int id)
        {
            using (RegistroData db = new RegistroData())
            {
                var i = db.alm_alumno.Find(id);
                db.alm_alumno.Remove(i);
                db.SaveChanges();

            }
            return RedirectToAction("/");
        }

        // POST: Alumno/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

RegistroAlumno/RegistroAlumno/Views/Alumno/Editar.cshtml
@model RegistroAlumno.Models.ListViewModel.AlumnoViewModel
@{
    ViewBag.Title = "Nuevo";
    List<SelectListItem> items = ViewBag.items;
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm("Editar", "Alumno", FormMethod.Post))
{

    @Html.HiddenFor(d=>d.Alm_id)


    @Html.LabelFor(d => d.Alm_nombre)
    @Html.TextBoxFor(d => d.Alm_nombre, "", new { @class = "form-control" });

    @Html.LabelFor(d => d.Alm_edad)
    @Html.TextBoxFor(d => d.Alm_edad, "", new { @class = "form-control" });

    @Html.LabelFor(d => d.Alm_sexo)
    @Html.TextBoxFor(d => d.Alm_sexo, "", new { @class = "form-control" });

    /*@Html.LabelFor(d => d.Alm_nombre)
    @Html.DropDownList("Grados", items, "-Seleccionar grado-", new { @class = "form-control"});*/

    @Html.LabelFor(d => d.Alm_id_grd)
    @Html.TextBoxFor(d => d.Alm_id_grd, "", new { @class = "form-control" });


    @Html.LabelFor(d => d.Alm_observaciones)
    @Html.TextBoxFor(d => d.Alm_observaciones, "", new { @class = "form-control" });

    @Html.HiddenFor(d => d.Created_at)
    

    @Html.LabelFor(d => d.Updated_at)
    <br />
    @Html.EditorFor(d => d.Updated_at, "", new { @class = "form-control" });

    <div style="padding-top: 5px">
        <input type="submit" value="Guardar" class="btn btn-primary" />
    </div>

}

RegistroAlumno/RegistroAlumno/Views/Alumno/Index.cshtml
@model List<RegistroAlumno.Models.ListViewModel.ListAlumnoViewModel>
@{
    ViewBag.Title = "Alumnos";
}

<h2>@ViewBag.Title</h2>

<div class="row" style="text-align:right; padding:5px">
    <a href="~/Alumno/Nuevo" class="btn btn-primary">Nuevo Alumno</a>
</div>

<div class="row">
    <div class="col-md-12">
        <table class="table">
            <tr>
                <th>#</th>
                <th>Nombre</th>
                <th>Edad</th>
                <th>Sexo</th>
                <th>Grado</th>
                <th>Observaciones</th>
                <th>Fecha de Creación</th>
                <th>Fecha de Actualizacion</th>
                <th>Accion</th>

            </tr>
            @foreach (var i in Model)
            {
                <tr>
                    <td>@i.Alm_id</td>
                    <td>@i.Alm_nombre</td>
                    <td>@i.Alm_edad</td>
                    <td>@i.Alm_sexo</td>
                    <td>@i.Alm_id_grd</td>
                    <td>@i.Alm_observaciones</td>
                    <td>@i.Created_at</td>
                    <td>@i.Updated_at</td>
                    <td>
                        <a href="~/Alumno/Editar/@i.Alm_id" class="btn btn-success">Editar</a>
                        <a href="~/Alumno/Eliminar/@i.Alm_id" class="btn alert-danger">Eliminar</a>
                    </td>
                </tr>
            }
        </table>

    </div>

</div>

RegistroAlumno/RegistroAlumno/Views/Alumno/Nuevo.cshtml
@model RegistroAlumno.Models.ListViewModel.AlumnoViewModel
@{
    //ViewBag.Title = "Nuevo";
    //List<SelectListItem> items = ViewBag.items;
}

<h2>Nuevo</h2>

@using (Html.BeginForm("Nuevo", "Alumno", FormMethod.Post))
{
    <div>
        @Html.LabelFor(d => d.Alm_id)

        @Html.TextBoxFor(d => d.Alm_id, "", new { @class = "form-control" })
        @Html.ValidationMessageFor(d => d.Alm_id, null, new { @class = "red" })
    </div>


    <div>
        @Html.LabelFor(d => d.Alm_nombre)
        @Html.TextBoxFor(d => d.Alm_nombre, "", new { @class = "form-control" })
        @Html.ValidationMessageFor(d => d.Alm_nombre, null, new { @class = "red" })
    </div>

    <div>
        @Html.LabelFor(d => d.Alm_edad)
        @Html.TextBoxFor(d => d.Alm_edad, "", new { @class = "form-control" })
        @Html.ValidationMessageFor(d => d.Alm_edad, null, new { @class = "red" })
    </div>

    <div>
        @Html.LabelFor(d => d.Alm_sexo)
        @Html.TextBoxFor(d => d.Alm_sexo, "", new { @class = "form-control" })
        @Html.ValidationMessageFor(d => d.Alm_sexo, null, new { @class = "red" })

    </div>

    <div>
        @Html.LabelFor(d => d.Alm_id_grd)
        @Html.TextBoxFor(d => d.Alm_id_grd, "", new { @class = "form-control" })
        @Html.ValidationMessageFor(d => d.Alm_nombre, null, new { @class = "red" })
    </div>
   




    <div>
        @Html.LabelFor(d => d.Alm_observaciones)
        @Html.TextBoxFor(d => d.Alm_observaciones, "", new { @class = "form-control" })
        @Html.ValidationMessageFor(d => d.Alm_observaciones, null, new { @class = "red" })
    </div>

    <div>
        @Html.LabelFor(d => d.Created_at)
        <br />
        @Html.EditorFor(d => d.Created_at, "", new { @class = "form-control" })
        @Html.ValidationMessageFor(d => d.Created_at, null, new { @class = "red" })
    </div>
    <br />

    <div>
        @Html.LabelFor(d => d.Updated_at)
        <br />
        @Html.EditorFor(d => d.Updated_at, "", new { @class = "form-control" })
        @Html.ValidationMessageFor(d => d.Updated_at, null, new { @class = "red" })
    </div>




    <div style="padding-top: 5px">
        <input type="submit" value="Guardar" class="btn btn-primary" />
    </div>

}