RegistroAlumno/RegistroAlumno/Models/ListViewModel/MateriaViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace RegistroAlumno.Models.ListViewModel
{
    public class MateriaViewModel
    {
        [Required]
        [Display(Name ="ID")]
        public int Mat_id { get; set; }
        [Required]
        [StringLength(100)]
        [Display(Name = "MATERIA")]
        public string Mat_nombre { get; set; }

        [Required]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [Display(Name = "FECHA DE CREACION")]
        public DateTime Created_at { get; set; }

        [Required]
        [DataType(DataType.Date)]
        [Display(Name = "FECHA DE ACTUALIZACION")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime Updated_at { get; set; }

        
    }
}

RegistroAlumno/RegistroAlumno/Controllers/MateriaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using RegistroAlumno.Models;
using RegistroAlumno.Models.ListViewModel;


namespace RegistroAlumno.Controllers
{
    public class MateriaController : Controller
    {
        // GET: Materia
        public ActionResult Index()
        {
            List<ListMateriaViewModel> lst;
            using (RegistroData db = new RegistroData())
            {
                lst = (from d in db.mat_materia
                       select new ListMateriaViewModel
                       {
                           Mat_id = d.mat_id,
                           Mat_nombre = d.mat_nombre,
                           Created_at = d.created_at,
                           Updated_at = d.created_at
                       }


                ).ToList();
            }
            return View(lst);
        }

        // GET: Materia/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Materia/Create
        public ActionResult Nuevo()
        {

            return View();
        }

        // POST: Materia/Create
        [HttpPost]
        public ActionResult Nuevo(MateriaViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    using(RegistroData db= new RegistroData())
                    {
                        var oMateria = new mat_materia();
                        
                            oMateria.mat_id = model.Mat_id;
                            oMateria.mat_nombre = model.Mat_nombre;
                            oMateria.created_at = model.Created_at;
                            oMateria.updated_at = model.Updated_at;

                            db.mat_materia.Add(oMateria);
                            db.SaveChanges();
                        

                    }
                    return RedirectToAction("/");
                }
                return View(model);

            }
            catch(Exception ex)
            {
                throw new Exception(ex.Message);
            }

            
           
            
        }


        public ActionResult Editar(int id)
        {
            MateriaViewModel oMateria = new MateriaViewModel();
            using (RegistroData db = new RegistroData())
            {
                var i = db.mat_materia.Find(id);
                oMateria.Mat_id = i.mat_id;
                oMateria.Mat_nombre = i.mat_nombre;
                oMateria.Created_at = i.created_at;
                oMateria.Updated_at = i.updated_at;
            }
            return View(oMateria);
        }

        [HttpPost]
        public ActionResult Editar(MateriaViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    using (RegistroData db = new RegistroData())
                    {
                        var oMateria = db.mat_materia.Find(model.Mat_id);

                        oMateria.mat_id = model.Mat_id;
                        oMateria.mat_nombre = model.Mat_nombre;
                        oMateria.created_at = model.Created_at;
                        oMateria.updated_at = model.Updated_at;

                        db.Entry(oMateria).State = System.Data.Entity.EntityState.Modified;
                        db.SaveChanges();


                    }
                    return RedirectToAction("/");
                }
                return View(model);
            }
            catch
            {
                return View();
            }
        }

        

        // GET: Materia/Delete/5
        public ActionResult Eliminar(int id)
        {
            using (RegistroData db = new RegistroData())
            {
                var i = db.mat_materia.Find(id);
                db.mat_materia.Remove(i);
                db.SaveChanges();

            }
            return RedirectToAction("/");
        }

        // POST: Materia/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

RegistroAlumno/RegistroAlumno/Views/Materia/Editar.cshtml
@model RegistroAlumno.Models.ListViewModel.MateriaViewModel
@{
    ViewBag.Title = "Editar";
}


<h2>@ViewBag.Title</h2>

@using (Html.BeginForm("Editar", "Materia", FormMethod.Post))
{

    @Html.HiddenFor(d => d.Mat_id);

    
    @Html.LabelFor(d => d.Mat_nombre)
    @Html.TextBoxFor(d => d.Mat_nombre, "", new { @class = "form-control" });


    @Html.HiddenFor(d => d.Created_at);
    

    @Html.LabelFor(d => d.Updated_at)
    <br />
    @Html.EditorFor(d => d.Updated_at, "", new { @class = "form-control" });



    <div style="padding-top: 5px">
        <input type="submit" value="Guardar" class="btn btn-primary" />
    </div>

}

RegistroAlumno/RegistroAlumno/Views/Materia/Index.cshtml
@model List<RegistroAlumno.Models.ListViewModel.ListMateriaViewModel>
@{
    ViewBag.Title = "Materia";
}

<h2>@ViewBag.Title</h2>

<div class="row" style="text-align:right; padding:5px">
    <a href="~/Materia/Nuevo" class="btn btn-primary">Nueva Materia</a>
</div>

<div class="row">
    <div class="col-md-12">
        <table class="table">
            <tr>
                <th>#</th>
                <th>Nombre Materia</th>
                <th>Fecha de Creación</th>
                <th>Fecha de Actualizacion</th>
                <th>Accion</th>

            </tr>
            @foreach (var i in Model)
            {
                <tr>
                <td>@i.Mat_id</td>
                <td>@i.Mat_nombre</td>
                <td>@i.Created_at</td>
                <td>@i.Updated_at</td>
                <td>
                    <a href="~/Materia/Editar/@i.Mat_id" class="btn btn-success">Editar</a>
                    <a href="~/Materia/Eliminar/@i.Mat_id" class="btn alert-danger">Eliminar</a>
                </td>
                </tr>
            }
        </table>

    </div>

</div>

RegistroAlumno/RegistroAlumno/Views/Materia/Nuevo.cshtml
@model RegistroAlumno.Models.ListViewModel.MateriaViewModel
@{
    ViewBag.Title = "Nuevo";
}


<h2>@ViewBag.Title</h2>

@using (Html.BeginForm("Nuevo", "Materia", FormMethod.Post))
{
    <div>
        @Html.LabelFor(d => d.Mat_id)

        @Html.TextBoxFor(d => d.Mat_id, "", new { @class = "form-control" })
        @Html.ValidationMessageFor(d => d.Mat_id, null, new { @class = "red" })
    </div>
    

    <div>
        @Html.LabelFor(d => d.Mat_nombre)
        @Html.TextBoxFor(d => d.Mat_nombre, "", new { @class = "form-control" })
        @Html.ValidationMessageFor(d => d.Mat_nombre, "", new { @class = "red" })
    </div>
    

    <div>
        @Html.LabelFor(d => d.Created_at)
        <br />
        @Html.EditorFor(d => d.Created_at, "", new { @class = "form-control" })
        @Html.ValidationMessageFor(d => d.Created_at, null, new { @class = "red" })
    </div>
    
    <br />
    <div>
        @Html.LabelFor(d => d.Updated_at)
        <br />
        @Html.EditorFor(d => d.Updated_at, "", new { @class = "form-control" })
        @Html.ValidationMessageFor(d => d.Updated_at, null, new { @class = "red" })
    </div>
   

    

    <div style="padding-top: 5px">
        <input type="submit" value="Guardar" class="btn btn-primary"/>
    </div>

}